name: plant_ui
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_analytics: ^10.3.0
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^14.0.0+1
  flutter_secure_storage: ^5.0.2
  flutter_tts: ^3.6.1
  get: 4.6.1
  http: ^0.13.4
  in_app_update: ^4.0.1
  local_auth: ^1.1.11
  lottie: ^1.2.2
  sliding_up_panel: ^2.0.0+1
  speech_to_text: ^6.1.0
  upgrader: ^5.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lootie/
